image: maven:3.8-openjdk-11git

default:
  tags:
    - shellLocal

stages:
  - test

Tests with Allure:
  stage: test
  script:
    - "curl -X POST --fail -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/39650110/trigger/pipeline"
    - mvn clean
    - mvn test
    - mvn allure:serve
  artifacts:
    paths:
      - target\site\allure-maven-plugin\*