image: maven:3.8-openjdk-11

stages:
  - test

Tests with Allure:
  stage: test
  script:
    - mvn clean
    - mvn test
    - mvn allure:serve
  artifacts:
    paths:
      - target\site\allure-maven-plugin\*